# Generated by Django 4.1.2 on 2022-10-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_bird_birds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Birds',
            new_name='Bird',
        ),
    ]
